[tool.nbqa.addopts]
flake8 = [
    "--ignore=E501,W503"
]
[tool.pytest.ini_options]
addopts = "--ignore-glob=Untitled* --ignore=snippets.ipynb --ignore-glob=draft* --ignore-glob=tfidf* --ignore-glob=word_frequencies* --ignore-glob=info_about* --ignore-glob=Make_PDFs*"